name: Deploy to Cloudflare Workers (Development)

on:
  push:
    branches:
      - develop
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify wrangler.toml exists
        run: |
          if [ ! -f wrangler.toml ]; then
            echo "❌ Error: wrangler.toml not found in repository root"
            exit 1
          fi
          echo "✅ wrangler.toml found"
          cat wrangler.toml

      - name: Deploy to Cloudflare Workers (Development)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env development
